### ISSUE TITLE
建议：改善Roam2anki引用文字的样式

### ISSUE THREAD

**Issue by xxhk-org** [swarma/anki-tools#12]
目前，Roam里的笔记如果是从内部其他block里引用的话，在转入ANKI以后，处理方式是这样的：将引用文本外部的英文双引号替换为 下划线标签u 。

当前方式有一个bug：

1、仅仅支持block开头是引用文本的处理，中间有文字是引用的话，不支持；
2、并且当有两句引用连着在一起时，会处理错误，即两对引号只会替换最外边两个，会保留中间两个引号；

希望改进的地方：
1、支持引用的文字替换引号为下划线u标签；
2、当两句引用连续时，即两对引号出现时，能正确替换。

参考：
1、这是Roam里笔记效果：https://www.jianguoyun.com/p/DXQoMm8Q89bQBxiQ0sgD 
2、这是Roam里笔记素材：https://www.jianguoyun.com/p/DQgDjfEQ89bQBxiX0sgD 
3、这是转换后的素材：https://www.jianguoyun.com/p/DcXvPS0Q89bQBxia0sgD 

期待改进，辛苦pimgeek   Thanks♪(･ω･)ﾉ

**Comment by pimgeek** [comment]
我正在看这个问题，有空会修改。 @LeoChanXY

**Comment by pimgeek** [comment]
今天刚刚修改过一版，可以把 Roam 导出的 `"text"` 替换为 `<u>text</u>` 先试用一下，有问题及时反馈吧。

**Comment by pimgeek** [comment]
实际使用未发现问题，关闭 Issue
