### ISSUE TITLE
建议增加葫芦笔记转Anki工具

### ISSUE THREAD

**Issue by yangyihl** [swarma/anki-tools#13]
1.在  https://hintsnet.com/tools/roam2anki/index.html  增加葫芦笔记工具入口。
2.实现和Roam to Anki工具一样的功能，即：在左侧粘贴一段 葫芦笔记, 在右侧获取 Anki CSV。

**Comment by pimgeek** [comment]
已经增加了 hulu2anki 工具，可以使用了。

https://hintsnet.com/tools/hulu2anki/
