### ISSUE TITLE
md2anki，导出文字格式不对，带html标签

### ISSUE THREAD

**Issue by EngineerLeonJ** [swarma/anki-tools#2]
## 问题描述：
markdown导入anki后带格式显示不对，带不明字符
这是工具导出页面的：
![image](https://user-images.githubusercontent.com/50700790/84729809-a9b69000-afa5-11ea-9546-6f3a29db08a1.png)
这是导入anki后的样子：
![image](https://user-images.githubusercontent.com/50700790/84729847-c0f57d80-afa5-11ea-9675-b47b74ee462e.png)
原始文本见附件，因md文件不能上传，改扩展名为.txt
## 工具
系统：win10 2004
编辑软件：Obsdian,Typora都有编辑
浏览器：Chromium Edge

**Comment by pimgeek** [comment]
@EngineerLeonJ 感谢及时反馈，我正在看

**Comment by EngineerLeonJ** [comment]
抱歉，补充说明：
该问题只出现在一个问题对应答案分几行的情况，一个问题对应一个答案是正常的，即：
![image](https://user-images.githubusercontent.com/50700790/84730623-bcca5f80-afa7-11ea-83df-768da7dcc5a9.png)
![image](https://user-images.githubusercontent.com/50700790/84730625-bfc55000-afa7-11ea-8e0e-990b0f3dd021.png)

**Comment by pimgeek** [comment]
你的原始文本输入在哪里？我没看到 TXT 文件啊？

> 抱歉，补充说明：
> 该问题只出现在一个问题对应答案分几行的情况，一个问题对应一个答案是正常的

另外，你有没有看到这个选项？

![image](https://user-images.githubusercontent.com/1609306/84730787-c795ec00-afc9-11ea-85a7-42b4fb951c85.png)

**Comment by EngineerLeonJ** [comment]
> 你的原始文本输入在哪里？我没看到 TXT 文件啊？
> 
> > 抱歉，补充说明：
> > 该问题只出现在一个问题对应答案分几行的情况，一个问题对应一个答案是正常的
> 
> 另外，你有没有看到这个选项？
> 
> ![image](https://user-images.githubusercontent.com/1609306/84730787-c795ec00-afc9-11ea-85a7-42b4fb951c85.png)

你好，是这个，选中后正常了；这个一直是选的不知道什么时候点错取消勾选了，感谢

**Comment by ankiwikicom** [comment]
辛苦pimgeek，这里发现两个问题。

### 反馈1：roam2anki中序号列表的判断问题

初衷：当只有一条文字和一条图片构成答案时，文字和图片都不添加序号列表

问题：使用中发现这个规则有bug，之前是三条文字+一条图片时该带序号没有带序号，这个应该是当时改的时候新增的bug。


![mark](http://myself.anki.wiki/mpic/20200624/F3OHHee6l9cI.png)

![mark](http://myself.anki.wiki/mpic/20200624/qMNKd6UiJOki.png)

### 反馈2：roam中通过block ref添加的block在复制出来后，会自动加上英文双引号在句首句尾，这些双引导和转换格式后格式标签如 <span class="bold">这样的双引号混淆，导致格式失效。

修复建议：在转换前自动去掉bolck ref字段的引号；更好的建议是将这些双引号替换成 <span class="ref">字段内容</span>，这样配合Anki模板可以更好地显示文字来源。（素材见下面第18行）


源文件如下：https://www.jianguoyun.com/p/DQiRNRYQ89bQBxiAuqYD

**Comment by pimgeek** [comment]
> 辛苦pimgeek，这里发现两个问题。
> 
> ### 反馈1：roam2anki中序号列表的判断问题 ...
> 
> ### 反馈2：roam中通过block ref添加的block在复制出来后，...

每个反馈单独创建一条 Issue 这样更容易跟踪哦~ 我来搬运一下：

* 反馈1 - #3 
* 反馈2 - #4
