### ISSUE TITLE
roam 中通过 block ref 添加的 block 在复制出来后，会自动加上英文双引号在句首句尾

### ISSUE THREAD

**Issue by pimgeek** [swarma/anki-tools#4]
@ankiwikicom 提到

roam 中通过 block ref 添加的 block 在复制出来后，会自动加上英文双引号在句首句尾，这些双引导和转换格式后格式标签如 `<span class="bold">` 这样的双引号混淆，导致格式失效。

修复建议：在转换前自动去掉block ref字段的引号；更好的建议是将这些双引号替换成 `<span class="ref">字段内容</span>`，这样配合 Anki 模板可以更好地显示文字来源。（素材见下面第18行）

源文件如下：https://www.jianguoyun.com/p/DQiRNRYQ89bQBxiAuqYD

**Comment by xxhk-org** [comment]
第一次用issue还不太会用，下次我分开提交哈

**Comment by pimgeek** [comment]
> 第一次用issue还不太会用，下次我分开提交哈

拥抱开源协作开发，我们又迈出了重要的一步~ 😎

**Comment by pimgeek** [comment]
双引号问题已经修正

@ankiwikicom 可以检查一下

**Comment by pimgeek** [comment]
与 Leo 确认过，问题已解决，可以关闭
