### ISSUE TITLE
Roam2anki中ref的字段的建议

### ISSUE THREAD

**Issue by xxhk-org** [swarma/anki-tools#5]
当前对于引用字段的双引号处理是保留，但基于以下两点考虑，建议将替换成标签<span class="ref">和</span>

1、文字被加上引号，不符合通常的阅读习惯；
2、和Roam里被添加下划线（如下图）的效果相差较大，不利于形成一致的体验。如果将引号替换成标签的话，可以结合ANKI中的CSS为其设置与Roam里一致的样式。

因此，建议供参考（当前未考虑实现难度和之后维护的复杂度），辛苦pimgeek考虑考虑

下图为Ref字段在Roam中的显示效果
![mark](http://myself.anki.wiki/mpic/20200624/8dvlCtW2nVRy.png)

**Comment by pimgeek** [comment]
换成下划线可以吗？

**Comment by xxhk-org** [comment]
> 换成下划线可以吗？

可以的，不过测试好像没有呢

**Comment by pimgeek** [comment]
> > 换成下划线可以吗？
> 
> 可以的，不过测试好像没有呢

目前是用 `<u>xxx</u>` 的方式实现的，如果整行内容带有双引号，那么在转换为 Anki 格式后，就应该变成 `<u>整行内容</u>`。我使用 https://www.jianguoyun.com/p/DQiRNRYQ89bQBxiAuqYD 测试可以生效。

**Comment by pimgeek** [comment]
经 Leo 确认，已经修复，可以关闭。
