### ISSUE TITLE
关于前三级目录所生成的笔记的问题

### ISSUE THREAD

**Issue by xxhk-org** [swarma/anki-tools#6]
转换过程中，咱们把这种：

问题：一级Block
答案：二级Block；二级Block；二级Block

这种层级汇总形成了笔记，和通常我们主动组织的“四级做问题，五级做答案”呈现在一起，但前者是从目录里提取自动生成的卡片。

这类汇总能不能把他们放到最后，而不是最开始

这样处理有几方面考虑：

1、我们本来的初衷是“先分后总”，就是当细节学完了以后，有个提纲挈领，但放在最前面往往是刚开始不需要，后面又看不到。

2、这种“先分后总”放在前面，让很多新人看不明白，常常误以为是生成错误了。

**Comment by pimgeek** [comment]
这个需求对大纲解析的顺序有要求，感觉还不能很快地改出来，初步思路就是把章节输出放在所有子节点处理完毕之后。 @LeoChanXY

**Comment by xxhk-org** [comment]
> 这个需求对大纲解析的顺序有要求，感觉还不能很快地改出来，初步思路就是把章节输出放在所有子节点处理完毕之后。 @LeoChanXY

可以的

**Comment by pimgeek** [comment]
先分后总的需求已经实现，经 Leo 测试多次后没发现问题，可以关闭
