### ISSUE TITLE
关于前三级自动形成书名号字段的bug

### ISSUE THREAD

**Issue by xxhk-org** [swarma/anki-tools#7]
据同学反映，当前三级存在 短横线 - 时，后面的内容就会丢失，在转换后的书名号字段里就会丢失短横线后面的内容。

![mark](http://myself.anki.wiki/mpic/20200724/9GnYwtsWkMwh.png)

**Comment by xxhk-org** [comment]
文字描述部分丢失，这里再补充一下哈：同学反映，当前三级中有短横线时，转换后短横线后面的文字就会丢失。

背景：前三级在转换时，自动形成一个字段，转入ANKI后存在于书名号字段中，用于交待笔记的出处为 哪本书 第几章 第几节 等等

**Comment by xxhk-org** [comment]
突然想到这个短横线可能是被误识别为 大纲序号 了，所以短横线后面的内容会被认为是 三级以外，就不识别了

**Comment by pimgeek** [comment]
今天晚上一定设法把这些都解决。😅

**Comment by pimgeek** [comment]
所有书名号内标题中出现的 `-`，都用 `·` 替换过了，你可以看看效果如何。 @LeoChanXY

**Comment by pimgeek** [comment]
与 Leo 核对过后，确认问题已解决，可以关闭
