### ISSUE TITLE
用户反馈半角空格影响转换

### ISSUE THREAD

**Issue by xxhk-org** [swarma/anki-tools#8]
![mark](http://myself.anki.wiki/mpic/20200731/QyfJn5AsP1YQ.jpg)

**Comment by xxhk-org** [comment]
如果还有其他细节需要确认，可以在圈子里找到帖主和这条帖子。

**Comment by pimgeek** [comment]
收到了，我检查一下

> 如果还有其他细节需要确认，可以在圈子里找到帖主和这条帖子。

**Comment by pimgeek** [comment]
已经检查过了，暂时没有发现代码本身的问题，可能与导出的操作方式有关。
